.PHONY: producer consumer all


producer:
	@echo "running typescript producer"
	npm i
	npm run test-producer

consumer:
	@echo "running typescript consumer"
	npm i
	npm run test-consumer

all: producer consumer