.PHONY: producer consumer all


producer:
	@echo "running go producer"
	cd producer/ && go run producer.go

consumer:
	@echo "running go consumer"
	cd consumer/ && go run consumer.go

all: producer consumer
